# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - uses: actions/checkout@v3.2.0

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: xmllint
        run: xmllint --schema codelist.xsd --noout xml/*

      - name: flake8 lint
        run: flake8 --exclude=pyenv,pyenv3 --ignore E501

  trigger:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Trigger a build on the codelists repo
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/version-') }}
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: codeforIATI/codelists
          token: ${{ secrets.TOKEN }}
          event-type: build
